// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// lmb
List lmb(NumericVector x, NumericVector y, NumericVector omega);
RcppExport SEXP spectral_lmb(SEXP xSEXP, SEXP ySEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    __result = Rcpp::wrap(lmb(x, y, omega));
    return __result;
END_RCPP
}
