# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Lomb-Scargle estimation function
#'
#' calculates the Lomb-Scargle estimation
#'
#' This wrapper function calls compiled C++ code, which does the job.
#'
#' @param x spatial vector
#' @param y data vector
#' @param omega frequency vector
lmb <- function(x, y, omega) {
    .Call('spectral_lmb', PACKAGE = 'spectral', x, y, omega)
}

